$script_mysql = <<-SCRIPT
    apt-get update && \
    apt-get install -y mysql-server-5.7 && \
    mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus = 1
  end 


  config.vm.define "mysqldb" do |mysql|
    mysql.vm.network "forwarded_port", guest: 80, host: 8089
    #rede privada com dhcp
    mysql.vm.network "private_network", type: "dhcp"
    #rede pública
    mysql.vm.network "public_network"
    #provision executa comandos na máquina criada ao rodar os privisioners
    mysql.vm.provision "shell", inline: "cat /configs/id_bionic.pub >> .ssh/authorized_keys"
    #comandos são automaticamente rodados como sudoers
    mysql.vm.provision "shell", inline: $script_mysql
    mysql.vm.provision "shell", inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
    mysql.vm.provision "shell", inline: "service mysql restart"
    #synced folder é uma pasta compartilhada entre o host e as VMs
    mysql.vm.synced_folder "./configs", "/configs"
  end
  config.vm.define "phpweb" do |phpweb|
    phpweb.vm.network "forwarded_port", guest:80, host:8089
    phpweb.vm.network "public_network", ip: "192.168.1.25"
    
    phpweb.vm.provision "shell", inline: "apt-get update && apt-get install -y puppet"
    phpweb.vm.provision "shell", inline: "puppet apply /vagrant/configs/manifests/phpweb.pp"
    
    phpweb.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "./configs/manifests"
      puppet.manifest_file = "phpweb.pp"
    end
  end

  config.vm.define "mysqldb2" do |mysqldb2|
    mysqldb2.vm.network "public_network", ip: "192.168.10.77"

    mysqldb2.vm.provision "shell",
            inline: "cat /vagrant/configs/id_bionic.pub >> .ssh/authorized_keys"
  end

  config.vm.define "ansible" do |ansible|
    ansible.vm.network "public_network", ip: "192.168.1.26"
    ansible.vm.provision "shell",
        inline: "apt-get update && \
                 apt-get install -y software-properties-common && \
                 apt-add-repository --yes --update ppa:ansible/ansible && \
                 apt-get install -y ansible"
    
    ansible.vm.provision "shell",
      inline: "cp /vagrant/id_bionic  /home/vagrant && \
            chmod 600 /home/vagrant/id_bionic"
    
    ansible.vm.provision "shell", 
            inline: "cp /vagrant/id_bionic /home/vagrant && \
                     chmod 600 /home/vagrant/id_bionic && \
                     chown vagrant:vagrant /home/vagrant/id_bionic"

    ansible.vm.provision "shell",
      inline: "ansible-playbook -i /vagrant/configs/ansible/hosts \
          /vagrant/configs/ansible/playbook.yml"
  end

  config.vm.define "phpweb2" do |phpweb2|
    phpweb2.vm.network "forwarded_port", guest: 8888, host: 8888
    phpweb2.vm.network "public_network", ip: "192.168.1.25"

    phpweb2.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 2
        vb.name = "ubuntu_bionic_php7"
    end
  end

  config.vm.define "memcached" do |memcached|
    memcached.vm.box = "centos/7"
    
    memcached.vm.provider "virtualbox" do |vb|
        vb.memory = 512
        vb.cpus = 1
        vb.name = "centos7_memcached"
    end
  end

end